#!/bin/bash
BASEDIR=/scripts

MYSQL_CLUSTER_MODE=${MYSQL_CLUSTER_MODE:-SemiSync}
MYSQL_USER=${MYSQL_USER:-root}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-$MYSQL_ROOT_PASSWORD}
MYSQL_NODES=${MYSQL_NODES}
MYSQL_PORT=${MYSQL_PORT-3306}
MYSQL_REPL_USER=${MYSQL_REPL_USER}
MYSQL_REPL_PASSWORD=${MYSQL_REPL_PASSWORD}

source $BASEDIR/util.sh
source $BASEDIR/mysql-cluster.sh
source $BASEDIR/mysql-mgrsp.sh
source $BASEDIR/mysql-semi-sync.sh
