#!/bin/bash
BASEDIR=/scripts

export MYSQL_CLUSTER_MODE=${MYSQL_CLUSTER_MODE:-SemiSync}
export MYSQL_USER=${MYSQL_USER:-root}
export MYSQL_PWD=${MYSQL_PASSWORD:-$MYSQL_ROOT_PASSWORD}
export MYSQL_NODES=${MYSQL_NODES}
export MYSQL_PORT=${MYSQL_PORT-3306}
export MYSQL_REPL_USER=${MYSQL_REPL_USER}
export MYSQL_REPL_PASSWORD=${MYSQL_REPL_PASSWORD}

export S3_ENDPOINT=${S3_ENDPOINT}
export S3_BUCKET=${S3_BUCKET}
export S3_PATH=${S3_PATH}
export S3_ACCESS_KEY=${S3_ACCESS_KEY}
export S3_SECURITY_KEY=${S3_SECURITY_KEY}
export MYSQL_BACKUP_OUTFILE=${MYSQL_BACKUP_OUTFILE:-backup}
export MYSQL_BACKUP_USE_ZLIB_COMPRESS=${MYSQL_BACKUP_USE_ZLIB_COMPRESS:-false}

source $BASEDIR/util.sh
source $BASEDIR/mysql-cluster.sh
source $BASEDIR/mysql-mgrsp.sh
source $BASEDIR/mysql-semi-sync.sh
source $BASEDIR/mysql-backup.sh
