kind: Deployment
apiVersion: apps/v1
metadata:
  name: rds-operator
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: rds-operator
  template:
    metadata:
      labels:
        k8s-app: rds-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: operator
          image: rumia/rds-operator
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
