kind: Redis
apiVersion: rds.hakurei.cn/v1alpha1
metadata:
  name: redis
spec:
  imagePullPolicy: Always
  storageClassName: hostpath
  password: abc
  masterReplicas: 3
  dataReplicas: 1
  timeZone: Asia/Shanghai
  redis:
    image: docker.io/bitnami/redis-cluster:6.2.5
    storageSize: 1Gi
    backupMethod: AOF
    command:
    - /bin/bash
    - -c
    args: 
    - |
      if ! [[ -f /opt/bitnami/redis/etc/redis.conf ]]; then
        cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
      fi

      podIndex=${HOSTNAME##*-}
      if [ $podIndex == 0 ]; then
        export REDIS_CLUSTER_CREATOR="yes"
      fi
      
      /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
    # readinessProbe:
    #   exec:
    #     command:
    #     - /bin/bash
    #     - -c
    #     - |
    #       redis-cli -a ${REDIS_PASSWORD} -p 6379 PING > /dev/null 2>&1
    #       if [ $? != 0 ];then
    #         echo "redis 6379 not ready"
    #         exit 1
    #       fi
    #   initialDelaySeconds: 35
    #   periodSeconds: 5
    #   timeoutSeconds: 4
    # livenessProbe:
    #   exec:
    #     command:
    #     - /bin/bash
    #     - -c
    #     - |
    #       redis-cli -a ${REDIS_PASSWORD} -p 6379 PING > /dev/null 2>&1
    #       if [ $? != 0 ];then
    #         echo "redis 6379 not ready"
    #         exit 1
    #       fi
    #   initialDelaySeconds: 55
    #   periodSeconds: 5
    #   timeoutSeconds: 4
  proxy:
    image: rumia/redis-cluster-proxy:1.0-beta2
    replicas: 1
    nodePort: 32337 #set to zero if want use random nodeport,delete this field will disable nodeport
    # readinessProbe:
    #   exec:
    #     command:
    #     - /bin/bash
    #     - -c
    #     - |
    #       redis-cli -a ${REDIS_PASSWORD} -p 6379 PING > /dev/null 2>&1
    #       if [ $? != 0 ];then
    #         echo "redis 6379 not ready"
    #         exit 1
    #       fi
    #   initialDelaySeconds: 35
    #   periodSeconds: 5
    #   timeoutSeconds: 4
    # livenessProbe:
    #   exec:
    #     command:
    #     - /bin/bash
    #     - -c
    #     - |
    #       redis-cli -a ${REDIS_PASSWORD} -p 6379 PING > /dev/null 2>&1
    #       if [ $? != 0 ];then
    #         echo "redis 6379 not ready"
    #         exit 1
    #       fi
    #   initialDelaySeconds: 55
    #   periodSeconds: 5
    #   timeoutSeconds: 4