apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: rds-operator
  name: rds-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    k8s-app: rds-operator
