
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rds-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - post
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - post
- apiGroups:
  - ""
  resources:
  - pods/logs
  verbs:
  - create
  - get
  - list
  - post
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqlbackups/finalizers
  verbs:
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqlbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqls/finalizers
  verbs:
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - mysqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - proxysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.hakurei.cn
  resources:
  - proxysqls/finalizers
  verbs:
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - proxysqls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.hakurei.cn
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - rds.hakurei.cn
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - configMap
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - pod
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
