/*
MIT License

Copyright (c) 2021 Software Authors

Software Authors are:
    Xing Yu, email: yuxing951@gmail.com,yuxing951@hotmail.com
    Yi Zhou, email: 6098550@qq.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hakur/rds-operator/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KafkaLister helps list Kafkas.
// All objects returned here must be treated as read-only.
type KafkaLister interface {
	// List lists all Kafkas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Kafka, err error)
	// Kafkas returns an object that can list and get Kafkas.
	Kafkas(namespace string) KafkaNamespaceLister
	KafkaListerExpansion
}

// kafkaLister implements the KafkaLister interface.
type kafkaLister struct {
	indexer cache.Indexer
}

// NewKafkaLister returns a new KafkaLister.
func NewKafkaLister(indexer cache.Indexer) KafkaLister {
	return &kafkaLister{indexer: indexer}
}

// List lists all Kafkas in the indexer.
func (s *kafkaLister) List(selector labels.Selector) (ret []*v1alpha1.Kafka, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Kafka))
	})
	return ret, err
}

// Kafkas returns an object that can list and get Kafkas.
func (s *kafkaLister) Kafkas(namespace string) KafkaNamespaceLister {
	return kafkaNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KafkaNamespaceLister helps list and get Kafkas.
// All objects returned here must be treated as read-only.
type KafkaNamespaceLister interface {
	// List lists all Kafkas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Kafka, err error)
	// Get retrieves the Kafka from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Kafka, error)
	KafkaNamespaceListerExpansion
}

// kafkaNamespaceLister implements the KafkaNamespaceLister
// interface.
type kafkaNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Kafkas in the indexer for a given namespace.
func (s kafkaNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Kafka, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Kafka))
	})
	return ret, err
}

// Get retrieves the Kafka from the indexer for a given namespace and name.
func (s kafkaNamespaceLister) Get(name string) (*v1alpha1.Kafka, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kafka"), name)
	}
	return obj.(*v1alpha1.Kafka), nil
}
