/*
MIT License

Copyright (c) 2021 Software Authors

Software Authors are:
    Xing Yu, email: yuxing951@gmail.com,yuxing951@hotmail.com
    Yi Zhou, email: 6098550@qq.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hakur/rds-operator/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProxySQLLister helps list ProxySQLs.
// All objects returned here must be treated as read-only.
type ProxySQLLister interface {
	// List lists all ProxySQLs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ProxySQL, err error)
	// ProxySQLs returns an object that can list and get ProxySQLs.
	ProxySQLs(namespace string) ProxySQLNamespaceLister
	ProxySQLListerExpansion
}

// proxySQLLister implements the ProxySQLLister interface.
type proxySQLLister struct {
	indexer cache.Indexer
}

// NewProxySQLLister returns a new ProxySQLLister.
func NewProxySQLLister(indexer cache.Indexer) ProxySQLLister {
	return &proxySQLLister{indexer: indexer}
}

// List lists all ProxySQLs in the indexer.
func (s *proxySQLLister) List(selector labels.Selector) (ret []*v1alpha1.ProxySQL, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ProxySQL))
	})
	return ret, err
}

// ProxySQLs returns an object that can list and get ProxySQLs.
func (s *proxySQLLister) ProxySQLs(namespace string) ProxySQLNamespaceLister {
	return proxySQLNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ProxySQLNamespaceLister helps list and get ProxySQLs.
// All objects returned here must be treated as read-only.
type ProxySQLNamespaceLister interface {
	// List lists all ProxySQLs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ProxySQL, err error)
	// Get retrieves the ProxySQL from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ProxySQL, error)
	ProxySQLNamespaceListerExpansion
}

// proxySQLNamespaceLister implements the ProxySQLNamespaceLister
// interface.
type proxySQLNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ProxySQLs in the indexer for a given namespace.
func (s proxySQLNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ProxySQL, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ProxySQL))
	})
	return ret, err
}

// Get retrieves the ProxySQL from the indexer for a given namespace and name.
func (s proxySQLNamespaceLister) Get(name string) (*v1alpha1.ProxySQL, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("proxysql"), name)
	}
	return obj.(*v1alpha1.ProxySQL), nil
}
