apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
  
images:
- name: operator
  newName: rumia/rds-operator
  newTag: v0.0.2
namespace: kube-system
