kind: MysqlBackup
apiVersion: rds.hakurei.cn/v1alpha1
metadata:
  name: yuxing
spec:
  s3:
    endpoint: http://192.168.1.4
    bucket: mysql-backup
    accessKey: 
    securityKey: 
    path: "/12"
  timeZone: Asia/Shanghai
  schedule: "*/1 * * * *"
  clusterMode: MGRSP
  image: rumia/rds-sidecar
  storageSize: 1Gi
  username: root
  password: zerocube
  # useZlibCompress: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
  address:
  - host: yuxing-mysql-0
    port: 3306
  - host: yuxing-mysql-1
    port: 3306
  - host: yuxing-mysql-2
    port: 3306
