kind: MysqlBackup
apiVersion: rds.hakurei.cn/v1alpha1
metadata:
  name: yuxing
spec:
  s3:
    endpoint: http://192.168.113.175:30817
    bucket: mysql-backup
    accessKey: openpitrixminioaccesskey
    securityKey: openpitrixminiosecretkey
    path: "/12"
  timeZone: Asia/Shanghai
  schedule: "*/1 * * * *"
  clusterMode: MGRSP
  image: minio/mc:RELEASE.2021-09-02T09-21-27Z
  storageSize: 1Gi
  username: root
  password: zerocube
  # useZlibCompress: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 256Mi
  mysql:
  - host: yuxing-mysql-0
    port: 3306
  - host: yuxing-mysql-1
    port: 3306
  - host: yuxing-mysql-2
    port: 3306
  initContainerImage: mysql/mysql-server:5.7.34
  initContainerCommand:
  - /bin/bash
  initContainerArgs:
  - -c
  - |
    #!/bin/bash
    rm -rf /data/backup
    source /scripts/mysql.sh
    BackupMaster /data/backup_$(date '+%Y-%m-%d_%H_%M')
  command:
  - /bin/bash
  args:
  - -c
  - |
    #!/bin/bash
    source /scripts/mysql.sh
    UploadToS3 /data
